name: Create Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.*'
    branches:
    - main

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    
  create_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set RELEASE_VERSION ENV var
      run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
    - name: create distribution
      run: make dist
    - name: create release
      env:
        OUT_BASE: ./bin/${{ env.RELEASE_VERSION }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ env.RELEASE_VERSION }} \
        -t "Default CSP Header Plugin ${{ env.RELEASE_VERSION }}" \
        "defaultcsp-plugin.tar.gz"