name: Run gotest with testcontainers support
on: 
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: install go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.20.0'
    - uses: actions/checkout@v2
    - name: lint
      run: make lint
    - name: run go test
      run: make test
