name: Run gotest
on:
  workflow_call:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: install go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.20.0'
    - uses: actions/checkout@v2
    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2023.1.2"
        install-go: false
    - name: lint
      run: make lint
    - name: run go test
      run: make test
